# Generated by Django 5.2.9 on 2025-12-13 08:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.IntegerField(verbose_name='Âge')),
                ('contact_consent', models.BooleanField(default=False, verbose_name='Consentement aux contacts')),
                ('data_share_consent', models.BooleanField(default=False, verbose_name='Consentement au partage de données')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de l’issue')),
                ('description', models.TextField(verbose_name='Description de l’issue')),
                ('tag', models.CharField(choices=[('B', 'Bug'), ('F', 'Fonctionnalité'), ('T', 'Tâche')], max_length=2, verbose_name='Tag')),
                ('state', models.CharField(choices=[('T', 'À faire'), ('I', 'En cours'), ('C', 'Terminé')], default='T', max_length=2, verbose_name='État')),
                ('priority', models.CharField(choices=[('L', 'Faible'), ('M', 'Moyenne'), ('H', 'Haute')], max_length=1, verbose_name='Priorité')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('assignee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigné')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues_created', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du commentaire')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('issue_url', models.URLField(blank=True, verbose_name='URL de l’issue')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_created', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('issue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.issue', verbose_name='Issue liée')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du projet')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('type', models.CharField(choices=[('B', 'Back-end'), ('F', 'Front-end'), ('I', 'iOS'), ('A', 'Android')], max_length=1, verbose_name='Type de projet')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to=settings.AUTH_USER_MODEL, verbose_name='Auteur du projet')),
                ('contributors', models.ManyToManyField(blank=True, related_name='project_contributors', to=settings.AUTH_USER_MODEL, verbose_name='Contributeurs du projet')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.project', verbose_name='Projet lié'),
        ),
    ]
